variables:
  S3_BUCKET_NAME: ctjsrocks

stages:
  - build
  - deploy

build:
  image: node:10.5
  stage: build
  script: 
    - npm install
    - npm install gulp-cli -g
    - gulp build
    - cd ./app
    - npm install
    - cd ./..
  artifacts:
    paths: 
      - node_modules
      - app

lint:
  image: node:10.5
  stage: build
  when: on_success
  dependencies: 
    - build
  script: 
    - gulp lint

docs:
  image: node:10.5
  stage: build
  when: on_success
  dependencies: 
    - build
  script: 
    - gulp docs

release:
  when: manual
  image: node:10.5
  only: 
    - master
  stage: deploy
  script:
    - npm install
    - npm install gulp-cli -g
    - cd ./app
    - npm install
    - cd ./..
    - gulp release
