image: node:8.7

build:
  script: 
    - mv ./package2.json ./package.json
    - npm install
    - npm install gulp -g
    - mv ./package.json ./package2.json
    - gulp --release
    - cd ./app
    - npm install
