variables:
  S3_BUCKET_NAME: ctjsrocks

build:
  image: node:8.8
  stage: build
  script: 
    - mv ./package2.json ./package.json
    - npm install
    - npm install gulp -g
    - mv ./package.json ./package2.json
    - gulp --release
    - cd ./app
    - npm install

deploy:
  when: manual
  image: jacobcovington/node-awscli
  only: 
    - master
  stage: deploy
  script:
    - apt-get update -yy 
    - apt-get install -y wine1.7
    - mv ./package2.json ./package.json
    - npm install
    - npm install gulp -g
    - mv ./package.json ./package2.json
    - gulp --release
    - cd ./app
    - npm install
    - npm run dist
    - cd ./../
    - aws s3 cp ./builds/ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.7z"