language: node_js
node_js:
  - lts/*

before_install:
  - npm i -g gulp-cli
install:
  - cd ./app
  - npm install
  - cd ./../
  - npm install

stages:
  - lint
  - build
  - pack
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - gulp lint
    - stage: build
      script:
        - gulp build
      skip_cleanup: true
    - stage: build
      on:
        tags: true
        branch: master
      script:
        - gulp -f devSetup.gulpfile.js
        - gulp packages
      skip_cleanup: true

deploy:
  provider: releases # Github Releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  # see at gulpfile.js > zipPackages
  file: ./build/ctjs - v$TRAVIS_TAG/ct.js v$TRAVIS_TAG for *.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
    branch: master