[[actions]]
name = "play"
path = "ctjs.exe"
platform = "windows"

[[actions]]
name = "play"
path = "ctjs"
platform = "linux"

[[actions]]
name = "play"
path = "ctjs.app"
platform = "osx"

[[actions]]
name = "manual"
path = "https://docs.ctjs.rocks/"

[[actions]]
name = "Discord"
path = "https://discord.gg/CggbPkb"